### PR TITLE
Initial support for translation of messages using tinygettext and fmt.

### PR DESCRIPTION
**Pull request by jcsteh**
Re #13.

### CODE REVIEW

**Comment by jcsteh** [comment]
@Carlos-EstebanM @ElCrackLoko @Michael1972 @aizhidadi @betov75 @dingpengyu:
I've done the groundwork for translation with gettext (.po files). Before I merge this into the main release, it'd be good to get some testing from real translators. Not all of OSARA is translatable yet by far (and I don't plan to do all of that in this first piece of work), but enough of it is to get an idea of whether this is workable.

If you're willing, here's what you need to do to test:

1. Install the REAPER language pack you want to use.
2. Download [this Windows build](https://ci.appveyor.com/api/buildjobs/wm8ejt5tryp0k4wc/artifacts/installer/osara_pr477-458,680afc8b.exe) or [this Mac build](https://ci.appveyor.com/api/buildjobs/d6fmu337q16bx7th/artifacts/installer/osara_pr477-458,680afc8b.dmg) of OSARA and install it.
3. Download [this OSARA translation template](https://ci.appveyor.com/api/buildjobs/wm8ejt5tryp0k4wc/artifacts/locale/osara_pr477-458,680afc8b.pot).
4. Rename the template to have the same name as the REAPER language pack, but with a .po extension. For example, if you have installed German.ReaperLangpack, rename the template to German.po.
5. Edit the file with a text editor (must save in UTF-8) or you can use a po editor like PoEdit if you're familiar with it.
6. Translate some of the messages. You do that by putting the translated message inside the quotes on the msgstr line.
7. Once done, open your REAPER resource path (use the Show REAPER resource path action if you don't know where that is), create an osara folder, and inside the osara folder, create a locale directory.
8. Move or copy your edited .po file to that locale folder.
9. Restart REAPER.
10. Test whether your translations worked!

Thanks for your help.

**Comment by dingpengyu** [comment]
hi @jcsteh 
I used poedit to open osara_pr477-458, 680afc8b.pot prompts the following error:
Invalid file
 OK button 
The file cannot be opened.
The file may be corrupted or not in a format recognized by Poedit.
Poedit error
 OK button 
The file F:\downloads\chrome-downloads\osara_pr477-458,680afc8b.pot could not be loaded, it may be corrupted.
poedit version:
2.4.2
Thank you for your mood work.

**Comment by jcsteh** [comment]
Thanks for testing so quickly, @dingpengyu. Sorry; there was a slight bug in my tool for generating the .pot file. Please try [this updated translation template](https://ci.appveyor.com/api/buildjobs/fqqcyxn3pr59iun0/artifacts/locale/osara_pr477-459,def03e45.pot).

**Comment by dingpengyu** [comment]
> Thanks for testing so quickly, @dingpengyu. Sorry; there was a slight bug in my tool for generating the .pot file. Please try [this updated translation template](https://ci.appveyor.com/api/buildjobs/fqqcyxn3pr59iun0/artifacts/locale/osara_pr477-459,def03e45.pot).

The error has been resolved.

**Comment by betov75** [comment]
Wow, that's fantastic work! On the french side, can I use accented characters directly? For example: "Paramètres" ? Or do I use special codes? Also, a single quote, like in "L'item", do I need to escape it? I guess not, since it's within double quotes but only to make sure. I use REAPER in english but I know a lot of french speaking blind musicians who will be extremely pleased by that.

I'm sorry if my questions were already answered before, I'm having trouble adapting to github. I'm rapidly losing what's left of my sight these days.

**Comment by Christianlm** [comment]
I did my test and found no errors.
  Details:
  Tested on windows 10pro 2004.
  Reaper installed 6.23 64bit;
  OSARA buil provided by mr. James;
  language Italian (my native language). I created a draft translation using OSARA translation template and an incomplete translation for Reaper in Italian.
  As above, everything works correctly.
  
  As far as I know, there is not a complete translation for many languages in Reaper, but surely when Reaper becomes Multilanguage OSARA is not unprepared.
  Thanks @jcsteh, this is an excellent internationalization job.
  
  P.s. I'm not familiar with digital audio terms and Reaper terms, I think we will find an appropriate italian translator soon, @Lo-lo78, @GianlucaApollaro, @ranetto.

**Comment by dingpengyu** [comment]
> @Carlos-EstebanM @ElCrackLoko @Michael1972 @aizhidadi @betov75 @dingpengyu:
> I've done the groundwork for translation with gettext (.po files). Before I merge this into the main release, it'd be good to get some testing from real translators. Not all of OSARA is translatable yet by far (and I don't plan to do all of that in this first piece of work), but enough of it is to get an idea of whether this is workable.
> 
> If you're willing, here's what you need to do to test:
> 
> 1. Install the REAPER language pack you want to use.
> 2. Download [this Windows build](https://ci.appveyor.com/api/buildjobs/wm8ejt5tryp0k4wc/artifacts/installer/osara_pr477-458,680afc8b.exe) or [this Mac build](https://ci.appveyor.com/api/buildjobs/d6fmu337q16bx7th/artifacts/installer/osara_pr477-458,680afc8b.dmg) of OSARA and install it.
> 3. Download [this OSARA translation template](https://ci.appveyor.com/api/buildjobs/wm8ejt5tryp0k4wc/artifacts/locale/osara_pr477-458,680afc8b.pot).
> 4. Rename the template to have the same name as the REAPER language pack, but with a .po extension. For example, if you have installed German.ReaperLangpack, rename the template to German.po.
> 5. Edit the file with a text editor (must save in UTF-8) or you can use a po editor like PoEdit if you're familiar with it.
> 6. Translate some of the messages. You do that by putting the translated message inside the quotes on the msgstr line.
> 7. Once done, open your REAPER resource path (use the Show REAPER resource path action if you don't know where that is), create an osara folder, and inside the osara folder, create a locale directory.
> 8. Move or copy your edited .po file to that locale folder.
> 9. Restart REAPER.
> 10. Test whether your translations worked!
> 
> Thanks for your help.

hi @jcsteh 
Which specific directory is the REAPER resource path?
thanks

**Comment by jcsteh** [comment]
> On the french side, can I use accented characters directly? For example: "Paramètres" ?

You can use accented characters directly, but you must ensure the file is saved in UTF-8 encoding. How you do that depends on the text editor you're using, so I can't give specific instructions. For example, Notepad has an encoding combo box in its save dialog. Notepad++ has an Encoding menu where you can choose the encoding.

> Also, a single quote, like in "L'item", do I need to escape it?

No.

Thanks for testing.

**Comment by dingpengyu** [comment]
The translation has been successfully added to
Test passed
Test environment
windows10 2004
reaper 6.23

**Comment by ScottChesworth** [comment]
Super excited to see this thread taking off! It's gonna bring in a ton of new users, I can feel it in my bones. :)

Let me know when you're ready for more testers @jcsteh. On your command, I can fire off emails to make sure that people who've expressed interest in translating know this is moving.

**Comment by betov75** [comment]
It works great here. Using a user french language pack. Translated
different elements and tested them. A-1.
My Setup is:
- Windows 10 (all updates)
- Reaper 6 (last version)
- It works on my current installation of Reaper and within a portable
installation I'd installed only for testing it.
- Works with accents (like you already know but still)

I will also have to translate a full Reaper language pack in french because
the only one available is quite old.

Tell me when I can translate it all, if it's only for testing or if I can
translate the document now.

That part is a bit off topic but, quick motivating facts :
I know a lot of french canadian accessibility specialists that will be more
than pleased by that.
Just so you know how important it is, here, in Quebec, Canada, if a
software is not available in french, the government won't support it much.
If accessibility is not in french, no support for disabled kids. So,
really, it makes a very big difference. They're all on extremely old and
boring software because of the price and french availability. Reaper with
french OSARA will be the perfect sell now. Cheap for personal use and not
as expensive as Logic on the hardware side.

>

**Comment by windrofy** [comment]
msgctxt "OSARA Configuration"
msgid "Report &transport state (play, record, etc.)"
msgstr "報告走代播放、錄製等"

Chinese part becomes garbled.

**Comment by jcsteh** [comment]
> Chinese part becomes garbled.

Sorry. Fixed.

**Comment by windrofy** [comment]
Successful, thank you very much!

**Comment by windrofy** [comment]
This area cannot display the translated results.

msgctxt "Parameters"
msgid "Parameters"
msgstr ""

msgctxt "Parameters"
msgid "Parameter:"
msgstr ""

msgctxt "Parameters"
msgid "Value:"
msgstr ""

msgctxt "Parameters"
msgid "Filter:"
msgstr ""

msgctxt "Parameters"
msgid "&Close"
msgstr ""

Thanks!

**Comment by jcsteh** [comment]
Yes, I'm aware of that one. Making the Parameters dialogs translatable requires quite a bit of work I haven't gotten to yet. Sorry for the confusion.

**Comment by jcsteh** [comment]
Parameters dialogs are now translatable.

**Comment by windrofy** [comment]
The Parameters dialogs were successful, it's great, thank you for your 
hard work!

**Comment by windrofy** [comment]
I downloaded the source code and the following error occurred during compilation:

d:\osara\src\osara.h(23): fatal error C1083: 無法開啟包含檔案: 'tinygettext/dictionary.hpp': No such file or directory
scons: *** [build\x86\controlSurface.obj] Error 2
scons: building terminated because of errors.

Is there something missing?

**Comment by dingpengyu** [comment]
> I downloaded the source code and the following error occurred during compilation:
> 
> d:\osara\src\osara.h(23): fatal error C1083: 無法開啟包含檔案: 'tinygettext/dictionary.hpp': No such file or directory
> scons: *** [build\x86\controlSurface.obj] Error 2
> scons: building terminated because of errors.
> 
> Is there something missing?

Try it out git submodule update

**Comment by windrofy** [comment]
How do I to out git submodule update?
I use GitHub Desktop to clone.
I am very new to Programming.
Thank!

**Comment by dingpengyu** [comment]
> How do I to out git submodule update? I use GitHub Desktop to clone. I am very new to Programming. Thank!

First open the repository where you want to update the submodule.
Then open cmd or git bash
and finally type:
git submodule update

**Comment by windrofy** [comment]
Sorrry,
Where will open the repository?

**Comment by dingpengyu** [comment]
> Sorrry, Where will open the repository?

You can use Explorer to find the directory you cloned and enter it, then alt+d to locate the address bar and type cmd

**Comment by jcsteh** [comment]
@windrofy, note that if you only want to translate OSARA, you don't need to build from source. The latest translation template will always be available on the OSARA Snapshots page.

**Comment by windrofy** [comment]
Thanks a lot!
I succeed clone the submodule update.
I want to see the complete original code.
Thank you for your hard wor!

**Comment by windrofy** [comment]
Is there a spelling error in this item?

msgctxt "OSARA Configuration"
msgid "Report mar&kers during playback"

Should it be
msgid "Report &markers during playback"

**Comment by windrofy** [comment]
msgctxt "OSARA Configuration"
msgid "&Close"

at reaper track view
press ctrl+f12
the last is
Cancel btn

**Comment by jcsteh** [comment]
> msgid "Report mar&kers during playback"
> Should it be
> msgid "Report &markers during playback"

No. The "&" symbol is placed before the keyboard accelerator. Alt+m was taken already by another option, so we use alt+k here, which is why you see "&k".

> msgid "&Close"
> at reaper track view press ctrl+f12 the last is Cancel btn

That's a bug in the translation template. I'll fix it when I can.

Thanks.

**Comment by windrofy** [comment]
Peak Watcher lost
msgid "&Reset"
msgid "&Cancel"

thanks!

**Comment by jcsteh** [comment]
These last two issues are now fixed.

**Comment by windrofy** [comment]
Thanks for your hard work!

**Comment by windrofy** [comment]
What can i do the warning C4309:
thanks!

scons: Building targets ...
cl /Fobuild\x86\po_parser.obj /c include\tinygettext\src\po_parser.cpp 
/TP /EHsc /std:c++latest /W3 /WX /nologo /Ibuild\x86 /Isrc /Iinclude 
/Iinclude\WDL /Iinclude\tinygettext\include /Iinclude\fmt\include /Z7
po_parser.cpp
include\tinygettext\src\po_parser.cpp(337): error C2220: 將警告視為錯誤 
處理 - 沒有產生 'object' 檔案
include\tinygettext\src\po_parser.cpp(337): warning C4309: 
'static_cast': 轉換導致常數值遭截斷; 可能需要使用較大的類型
include\tinygettext\src\po_parser.cpp(338): warning C4309: 
'static_cast': 轉換導致常數值遭截斷; 可能需要使用較大的類型
include\tinygettext\src\po_parser.cpp(339): warning C4309: 
'static_cast': 轉換導致常數值遭截斷; 可能需要使用較大的類型
scons: *** [build\x86\po_parser.obj] Error 2
scons: building terminated because of errors.

**Comment by jcsteh** [comment]
What version of Visual Studio are you using? I don't see that here.

**Comment by windrofy** [comment]
haha!
I was used the old one.
It's ok after update to 2019.
Thanks!
