### ISSUE TITLE
OSARA Doesn't Build with xCode 10.2

### ISSUE THREAD

**Issue by mulcahy1000** [jcsteh/osara#202]
Looks like Apple broke the Mac OSX 10.14 SDK when including Carbon/Carbon.h. SWELL depends on this, and as such, fails to build. Updating to the head of the WDL repository doesn't help.

...
swell.cpp
In file included from include/WDL/WDL/swell/swell.cpp:40:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:34:10: fatal error: 'CarbonSound/CarbonSound.h' file not found
#include <CarbonSound/CarbonSound.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
...

Potentially hacking xCode and installing an older version of the Mac OS SDK would work, although I haven't yet tried it.

**Comment by mulcahy1000** [comment]
As per a response from Justin, apparently SWELL doesn't build with Xcode 10. So we should probably explicitly call out a requirement on Xcode 9 in the build instructions.
